### ISSUE TITLE
Check connection screen bug

### ISSUE THREAD

**Issue by ifuterman** [ifuterman/CIManagerProject#13]
1. Starting client without server
2. Starting server
3. Click "Проверка соединения"
4. Click OK - nothing, click "Отмена" - nothing

**Comment by ValeriusGC** [comment]
проверь!

**Comment by ifuterman** [comment]
Окно открылось, соединение сразу ок. Нажимаю кнопку "отмена" и вылетаю на экран
![image](https://user-images.githubusercontent.com/22131565/111310166-97759980-867e-11eb-945a-a6f495cbb6c9.png)

**Comment by ValeriusGC** [comment]
Сейчас если подключение так и не было установлено, приложение закрывается. Иначе переходит в форму **Авторизации**
