### ISSUE TITLE
Button "настройка подключение" is not working

### ISSUE THREAD

**Issue by ifuterman** [ifuterman/CIManagerProject#14]

**Comment by ValeriusGC** [comment]
Проверь!

**Comment by ifuterman** [comment]
При переходе по кнопке, форма появляется, но в консоли вываливается:
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: lock failed, path = 'C:\Users\ifuterman\Documents/GetStorage.gs' (OS Error: Процесс не может получить доступ к файлу, так как часть этого файла заблокирована другим процессом.

, errno = 33)

**Comment by ValeriusGC** [comment]
> При переходе по кнопке, форма появляется, но в консоли вываливается:
> [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: lock failed, path = 'C:\Users\ifuterman\Documents/GetStorage.gs' (OS Error: Процесс не может получить доступ к файлу, так как часть этого файла заблокирована другим процессом.
> 
> , errno = 33)

Поправил эту траблу. Сейчас кеш хранится прямо в директории экзешника. Но следует использовать его не напрямую через `GetStorage()..` а как-то так `Get.find<CacheProvider>().storage.write('connect', v.index);`
